version: '3'

networks:
  xgarage-network:

services:


##########   ANGULAR  ##############


  # angular:
  #   image: angular-images
  #   container_name: angular
  #   build:
  #     context: ../angular
  #     dockerfile: Dockerfile      
  #   networks:
  #     - xgarage-network
  #   ports:
  #    - 8080:80


##########   EUREKA  ##############


  eureka:
    image: longali/registryservice:latest
    container_name: eureka
    ports:
     - 8761:8761
    networks:
      - xgarage-network


##########   GATWAY  ##############


  gateway:
    image: longali/gatewayservice:latest
    container_name: gateway
    ports:
     - "6060:6060"
    networks:
      - xgarage-network
    depends_on:
      - eureka
    environment:
        EUREKA_SERVER_URL: http://eureka:8761/eureka/ 
        HOSTNAME: http://eureka
        KERNEL_URL: http://kernel:5050
        CORE_URL: http://core:4040



# networks:
#   spring:  # Define the new network

# services:
#   eureka:
#     image: longali/registryservice:latest
#     container_name: eureka
#     ports:
#       - "8761:8761"  # Expose the port to the host machine
#     networks:
#       - spring  # Connect eureka to the new network

#   gateway:
#     image: longali/gatewayservice:latest
#     container_name: gateway
#     ports:
#       - "6060:6060"  # Replace with your desired gateway port
#     depends_on:
#       - eureka  # Ensure Eureka starts first
#     # restart: on-failure
#     networks:
#       - spring  # Connect gateway to the new network
#     # environment:
#     #   - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://172.23.0.2:8761/  # Registration URL (can still use service name)
