version: '3.9'

services:
  registry:
    image: longali/registryservice:latest 
    ports:
      - "8756:8756"

  # Gateway
  gateway:
    image: longali/gatewayservice:latest
    ports:
      - "6060:6060"
    environment:
      - EUREKA_DEFAULT_ZONE=192.168.100.10:8756
      - HOSTNAME=192.168.100.10
      - KERNAL_PORT=5050
      - CORE_PORT=4040
  # # Angular application frontend
  # frontend:
  #   build: ./frontend  # Replace with the path to your Angular project directory
  #   ports:
  #     - "4200:4200"  # Adjust port if needed
  #   volumes:
  #     - ./frontend:/app  # Mount your Angular project directory inside the container
  #   depends_on:
  #     - registry  # Ensure registry is ready before frontend starts (if it interacts)

# Removed the database service definition since you're connecting to a remote one.
