version: '3'

networks:
  xgarage-network:

services:


##########   ANGULAR  ##############


  angular:
    image: longali/xgarageangular:latest
    container_name: angular   
    networks:
      - xgarage-network
    # ports:
    #  - 8080:80


##########   EUREKA  ##############


  eureka:
    image: longali/registryservice:latest
    container_name: eureka
    ports:
     - 8761:8761
    networks:
      - xgarage-network


##########   GATWAY  ##############


  gateway:
    image: longali/gatewayservice:latest
    container_name: gateway
    ports:
     - "6060:6060"
    networks:
      - xgarage-network
    depends_on:
      - eureka
    environment:
        EUREKA_SERVER_URL: http://eureka:8761/eureka/ 
        HOSTNAME: http://eureka
        KERNEL_URL: http://kernel:5050
        CORE_URL: http://core:4040


##########   KERNEL  ##############


  kernel:
    image: longali/kernelservice:latest
    container_name: kernel
    ports:
     - "5050:5050"
    networks:
      - xgarage-network
    depends_on:
      - eureka
    environment:
        EUREKA_SERVER_URL: http://eureka:8761/eureka/ 
        HOSTNAME: http://eureka


##########   CORE  ##############


  core:
    image: longali/coreservice:latest
    container_name: core
    ports:
     - "4040:4040"
    networks:
      - xgarage-network
    depends_on:
      - eureka
    environment:
        EUREKA_SERVER_URL: http://eureka:8761/eureka/ 
        HOSTNAME: http://eureka