apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-deployment-app
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-deployment-app
    spec:
      containers:
        - name: gateway
          image: longali/gatewayservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6060
          env:
            # Eureka URL
            - name: EUREKA_DEFAULT_ZONE
              valueFrom:
                configMapKeyRef:
                  name: xgarage-db-config
                  key: EUREKA_DEFAULT_ZONE
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: xgarage-db-config
                  key: HOSTNAME

              # Kernal URL
            - name: KERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: xgarage-db-config
                  key: KERNAL_PORT
              # Shop URL
            - name: SHOP_PORT
              valueFrom:
                configMapKeyRef:
                  name: xgarage-db-config
                  key: SHOP_PORT
              # CORE URL
            - name: CORE_PORT
              valueFrom:
                configMapKeyRef:
                  name: xgarage-db-config
                  key: CORE_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway-deployment-app
  ports:
    - protocol: "TCP"
      port: 30001
      targetPort: 6060
      nodePort: 30001
  type: NodePort
