server:
  port: 6060

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

    instance:
      hostname: ${HOSTNAME}

discovery:
  client:
    shutdownTimeoutSeconds: 10000
    refreshIntervalSeconds: 60000
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
spring:
  security:
    permitted-urls: /api/v1/document/**,/api/login/**,/api/v1/tenantType/**,/core/api/v1/brand/all, /core/api/v1/carModelType/all, /core/api/v1/carModelYear/all,/core/api/v1/category/all, /core/api/v1/subcategory/all, /api/changeUserRole/**, /api/v1/tenant/**,/api/token/refresh/**,/api/signup/**,/api/web/signup/**,/api/tenant/**,/api/v1/otp/verify/**,/api/v1/otp/forgetPassword/verify/**,/api/v1/otp/send/**,/api/recoverPassword/**,/api/forgetPassword/**,/v2/api-docs/**,/configuration/ui/**,/swagger-resources/**,/configuration/security/**,/v3/api-docs/**, /doc/swagger-ui.html, /doc/swagger-ui/**,/webjars/**
  application:
    name: xgarage-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: xgarage-kernel-service
          uri: ${KERNEL_URL}

          predicates:
            - Path=/api/**
          filters:
            - SetResponseHeader=Access-Control-Allow-Origin, *
            - SetResponseHeader=Access-Control-Allow-Methods, *
            - SetResponseHeader=Access-Control-Expose-Headers, *
        - id: xgarage-core-service
          uri: ${CORE_URL}
          predicates:
            - Path=/core/**
          filters:
            - AuthFilter
            - SetResponseHeader=Access-Control-Allow-Origin, *
            - SetResponseHeader=Access-Control-Allow-Methods, *
            - SetResponseHeader=Access-Control-Expose-Headers, *
        # - id: xgarage-shop-service
        #   uri: http://161.8.109.180:SHOP_PORT}
        #   predicates:
        #     - Path=/store/**
        #   filters:
        #     - AuthFilter
        #     - SetResponseHeader=Access-Control-Allow-Origin, *
        #     - SetResponseHeader=Access-Control-Allow-Methods, *
        #     - SetResponseHeader=Access-Control-Expose-Headers, *
